name: Deploy slides
on:
  push:
    branches: [main]
  # paths:  <-- Comentado temporalmente para forzar el test
  #   - 'slides/**'
  #   - 'mkslides.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install omegaconf mkslides

      - name: Build slides
        run: |
          mkslides build --config-file mkslides.yml slides/
          touch site/.nojekyll  
          ls -R ./site # Esto nos dirá en los logs qué archivos se han creado

      - name: Deploy to sin-slides
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          external_repository: apuntes-sergio/sin-slides
          deploy_key: ${{ secrets.SLIDES_DEPLOY_KEY }}
          publish_branch: gh-pages
          force_push: true