name: Deploy slides
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install omegaconf mkslides

      - name: Build slides
        run: |
          # 1. Limpiamos rastro anterior
          rm -rf site
          
          # 2. Construimos las slides
          mkslides build --config-file mkslides.yml slides/
          
          # 3. Evitamos que GitHub Pages use Jekyll
          touch site/.nojekyll

      - name: Deploy to sin-slides
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          external_repository: apuntes-sergio/sin-slides
          deploy_key: ${{ secrets.SLIDES_DEPLOY_KEY }}
          publish_branch: gh-pages
          force_push: true